spring.application.name=identity-service
server.port=8081

# PostgreSQL container connection
spring.datasource.url=jdbc:postgresql://postgres-identity:5433/identity_service_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=mcharo
spring.datasource.password=mcharo

# Eureka service discovery (Docker-based)
eureka.client.serviceUrl.defaultZone=http://eureka:password@discovery-server:8761/eureka
