spring.application.name=zone-service

server.port=8083
spring.datasource.url=jdbc:postgresql://postgres-zone:5435/zone_service_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=mcharo
spring.datasource.password=mcharo
eureka.client.serviceUrl.defaultZone=http://eureka:password@discovery-server:8761/eureka
spring.flyway.enabled=false

# Health and Management Endpoints Configuration
management.health.circuitbreaker.enable=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Resilience4j Properties for Circuit Breaker
resilience4j.circuitbreaker.instances.identity.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.identity.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.identity.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.identity.slidingWindowSize=100
resilience4j.circuitbreaker.instances.identity.failureRateThreshold=50
resilience4j.circuitbreaker.instances.identity.waitDurationInOpenState=10000ms
resilience4j.circuitbreaker.instances.identity.permittedNumberOfCallsInHalfOpenState=10
resilience4j.circuitbreaker.instances.identity.automaticTransitionFromOpenToHalfOpenEnabled=true

#Resilience4j Timeout Properties
resilience4j.timelimiter.instances.identity.timeout-duration=3s

#Resilience4j Retry Properties
resilience4j.retry.instances.identity.max-attempts=3
resilience4j.retry.instances.identity.wait-duration=5s
