spring.application.name=donor-service

spring.datasource.url=jdbc:postgresql://localhost:5433/donor_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082

spring.flyway.enabled=false
