spring.application.name=donor-service

spring.datasource.url=jdbc:postgresql://localhost:5432/donor_service_db
spring.datasource.username=nbts_user
spring.datasource.password=mcharo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8083

eureka.client.serviceUrl.defaultZone=http://eureka:password@localhost:8761/eureka

# Health and Management Endpoints Configuration
management.health.circuitbreaker.enable=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Resilience4j Properties for Circuit Breaker
resilience4j.circuitbreaker.instances.inventory.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventory.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.inventory.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.inventory.slidingWindowSize=100
resilience4j.circuitbreaker.instances.inventory.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventory.waitDurationInOpenState=10000ms
resilience4j.circuitbreaker.instances.inventory.permittedNumberOfCallsInHalfOpenState=10
resilience4j.circuitbreaker.instances.inventory.automaticTransitionFromOpenToHalfOpenEnabled=true
