spring.application.name=meeting-service

spring.datasource.url=jdbc:postgresql://localhost:5432/meeting_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082

server.servlet.context-path=/api/v1/meetings

eureka.client.serviceUrl.defaultZone=http://eureka:password@localhost:8761/eureka

jwt.private.key.path=file:/home/mcharo/projects/certs/private.pem
jwt.public.key.path=file:/home/mcharo/projects/certs/public.pem

# Health and Management Endpoints Configuration
management.health.circuitbreaker.enable=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Resilience4j Properties for Circuit Breaker
resilience4j.circuitbreaker.instances.meeting.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.meeting.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.meeting.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.meeting.slidingWindowSize=100
resilience4j.circuitbreaker.instances.meeting.failureRateThreshold=50
resilience4j.circuitbreaker.instances.meeting.waitDurationInOpenState=10000ms
resilience4j.circuitbreaker.instances.meeting.permittedNumberOfCallsInHalfOpenState=10
resilience4j.circuitbreaker.instances.meeting.automaticTransitionFromOpenToHalfOpenEnabled=true

#Resilience4j Timeout Properties
resilience4j.timelimiter.meeting.identity.timeout-duration=3s

#Resilience4j Retry Properties
resilience4j.retry.instances.identity.max-attempts=3
resilience4j.retry.instances.identity.wait-duration=5s